// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eolazcvsqrihmfxjwhtl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvbGF6Y3ZzcXJpaG1meGp3aHRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNzc0MDIsImV4cCI6MjA3NDY1MzQwMn0.At8SMN_Tk24ikHE9cXXPA2IHSIwQzomRjTPrBdKyI4Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});